export{ default as Home } from './Home/Home';
export{ default as CalendarEvents } from './Calendar/Calendar';
export{ default as Login } from './Login/Login';
export{ default as MyEvents } from './MyEvents/MyEvents';
export{ default as SignUp} from './SignUp/SignUp';
export{ default as Event } from './Event/Event';
export{ default as User } from './User/User';
export{ default as Create } from './Create/Create';
export{ default as Edit } from './Edit/Edit';
export{ default as ChangePassword } from './ChangePassword/ChangePassword';